minimumReleaseAge: 10080
overrides:
  '@typescript-eslint/project-service>typescript': 'npm:@typescript/typescript6@^6.0.2'
  '@typescript-eslint/tsconfig-utils>typescript': 'npm:@typescript/typescript6@^6.0.2'
  '@typescript-eslint/typescript-estree>typescript': 'npm:@typescript/typescript6@^6.0.2'
  '@typescript-eslint/utils>typescript': 'npm:@typescript/typescript6@^6.0.2'
peerDependencyRules:
  allowedVersions:
    typescript: '7'
