description: "Builds the metadata-editor project for macOS (Universal)"
inputs:
  gpg-private-key:
    description: "GPG private key for signing"
    required: true
  gpg-private-key-passphrase:
    description: "Passphrase of GPG private key for signing"
    required: true
  gpg-sign-key:
    description: "GPG key id for signing"
    required: true
name: "Build for macOS"
outputs:
  version:
    description: "App version"
    value: "${{ steps.version.outputs.value }}"
runs:
  steps:
    - env:
        GPG_PRIVATE_KEY: "${{ inputs.gpg-private-key }}"
        GPG_PRIVATE_KEY_PASSPHRASE: "${{ inputs.gpg-private-key-passphrase }}"
      name: "Import GPG key"
      shell: "bash"
      run: |
        gpg \
          --batch \
          --import \
          --no-tty \
          --passphrase-fd 3 \
          --pinentry-mode loopback \
          --yes \
          <<<"$GPG_PRIVATE_KEY" \
          3<<<"$GPG_PRIVATE_KEY_PASSPHRASE"
    - name: "Install pnpm"
      uses: "pnpm/action-setup@v6"
    - name: "Setup Node.js"
      uses: "actions/setup-node@v6"
      with:
        cache: "pnpm"
        node-version: 26
    - name: "Setup latest Rust toolchain"
      uses: "dtolnay/rust-toolchain@nightly"
      with:
        targets: "aarch64-apple-darwin,x86_64-apple-darwin"
    - name: "Install frontend dependencies"
      shell: "bash"
      run: "pnpm ci"
    - name: "Install backend dependencies"
      shell: "bash"
      run: "cargo fetch"
    - id: "product-name"
      name: "Get product name"
      uses: "SebRollen/toml-action@v1.2.0"
      with:
        field: "productName"
        file: "src-tauri/Tauri.toml"
    - id: "version"
      name: "Get version"
      uses: "SebRollen/toml-action@v1.2.0"
      with:
        field: "package.version"
        file: "src-tauri/Cargo.toml"
    - env:
        GPG_PRIVATE_KEY_PASSPHRASE: "${{ inputs.gpg-private-key-passphrase }}"
        GPG_SIGN_KEY: "${{ inputs.gpg-sign-key }}"
      id: "build"
      name: "Build"
      shell: "bash"
      run: |
        pnpm tauri build -b dmg -t universal-apple-darwin
        dir=$PWD/target/universal-apple-darwin/release/bundle/dmg
        name="${{ steps.product-name.outputs.value }}"
        ver="${{ steps.version.outputs.value }}"
        fullname=${name}_${ver}_universal
        if [[ ! -f $dir/$fullname.dmg ]]; then
          file=$(find "$dir" -type f -name '*.dmg')
          printf "\e[1;31mError: installer file name is wrong\e[m\n"
          printf "  expected: \e[33m%s/%s.dmg\e[m\n" "$dir" "$fullname"
          printf "  found: \e[33m%s\e[m\n" "$file"
          exit 1
        fi
        mkdir out
        mv "$dir/$fullname.dmg" "$GITHUB_WORKSPACE/out/$fullname.dmg"
        gpg \
          --batch \
          --detach-sign \
          --local-user "$GPG_SIGN_KEY" \
          --no-tty \
          --output "$GITHUB_WORKSPACE/out/$fullname.dmg.sig" \
          --passphrase-fd 0 \
          --pinentry-mode loopback \
          --yes \
          "$GITHUB_WORKSPACE/out/$fullname.dmg" \
          <<<"$GPG_PRIVATE_KEY_PASSPHRASE"
  using: "composite"
