jobs:
  build:
    permissions:
      contents: 'read'
    runs-on: '${{ matrix.host }}'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
      - if: "matrix.os == 'linux-appimage'"
        name: 'Build'
        uses: './.github/actions/build-linux-appimage'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - if: "matrix.os == 'linux-archlinux'"
        name: 'Build'
        uses: './.github/actions/build-linux-archlinux'
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg_private_key_passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg_sign_key: '${{ vars.GPG_SIGN_KEY }}'
          gpg_sign_key_keygrip: '${{ vars.GPG_SIGN_KEY_KEYGRIP }}'
      - if: "matrix.os == 'linux-deb'"
        name: 'Build'
        uses: './.github/actions/build-linux-deb'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - if: "matrix.os == 'linux-rpm'"
        name: 'Build'
        uses: './.github/actions/build-linux-rpm'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - if: "matrix.os == 'linux-tgz'"
        name: 'Build'
        uses: './.github/actions/build-linux-tgz'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - if: "matrix.os == 'macos'"
        name: 'Build'
        uses: './.github/actions/build-macos'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - if: "matrix.os == 'windows'"
        name: 'Build'
        uses: './.github/actions/build-windows'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: 'ubuntu-24.04'
            os: 'linux-appimage'
          - host: 'ubuntu-24.04'
            os: 'linux-archlinux'
          - host: 'ubuntu-24.04'
            os: 'linux-deb'
          - host: 'ubuntu-24.04'
            os: 'linux-rpm'
          - host: 'ubuntu-24.04'
            os: 'linux-tgz'
          - host: 'macos-26'
            os: 'macos'
          - host: 'windows-2025-vs2026'
            os: 'windows'
        os:
          - 'linux-appimage'
          - 'linux-archlinux'
          - 'linux-deb'
          - 'linux-rpm'
          - 'linux-tgz'
          - 'macos'
          - 'windows'
name: 'Build'
on:
  pull_request:
  push:
  workflow_dispatch:
