jobs:
  build:
    outputs:
      version: >-
        ${{
          case(
            matrix.os == 'linux-appimage',
            steps.build-linux-appimage.outputs.version,
            matrix.os == 'linux-archlinux',
            steps.build-linux-archlinux.outputs.version,
            matrix.os == 'linux-deb',
            steps.build-linux-deb.outputs.version,
            matrix.os == 'linux-rpm',
            steps.build-linux-rpm.outputs.version,
            matrix.os == 'linux-tgz',
            steps.build-linux-tgz.outputs.version,
            matrix.os == 'macos',
            steps.build-macos.outputs.version,
            matrix.os == 'windows',
            steps.build-windows.outputs.version,
            null
          )
        }}
    permissions:
      contents: 'read'
    runs-on: '${{ matrix.host }}'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
      - id: 'build-linux-appimage'
        if: "matrix.os == 'linux-appimage'"
        name: 'Build'
        uses: './.github/actions/build-linux-appimage'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - id: 'build-linux-archlinux'
        if: "matrix.os == 'linux-archlinux'"
        name: 'Build'
        uses: './.github/actions/build-linux-archlinux'
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg_private_key_passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg_sign_key: '${{ vars.GPG_SIGN_KEY }}'
          gpg_sign_key_keygrip: '${{ vars.GPG_SIGN_KEY_KEYGRIP }}'
      - id: 'build-linux-deb'
        if: "matrix.os == 'linux-deb'"
        name: 'Build'
        uses: './.github/actions/build-linux-deb'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - id: 'build-linux-rpm'
        if: "matrix.os == 'linux-rpm'"
        name: 'Build'
        uses: './.github/actions/build-linux-rpm'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - id: 'build-linux-tgz'
        if: "matrix.os == 'linux-tgz'"
        name: 'Build'
        uses: './.github/actions/build-linux-tgz'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - id: 'build-macos'
        if: "matrix.os == 'macos'"
        name: 'Build'
        uses: './.github/actions/build-macos'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - id: 'build-windows'
        if: "matrix.os == 'windows'"
        name: 'Build'
        uses: './.github/actions/build-windows'
        with:
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg-private-key-passphrase: >-
            ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          gpg-sign-key: '${{ vars.GPG_SIGN_KEY }}'
      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@v7'
        with:
          name: 'metadata-editor-${{ matrix.os }}'
          path: './out/'
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: 'ubuntu-24.04'
            os: 'linux-appimage'
          - host: 'ubuntu-24.04'
            os: 'linux-archlinux'
          - host: 'ubuntu-24.04'
            os: 'linux-deb'
          - host: 'ubuntu-24.04'
            os: 'linux-rpm'
          - host: 'ubuntu-24.04'
            os: 'linux-tgz'
          - host: 'macos-26'
            os: 'macos'
          - host: 'windows-2025-vs2026'
            os: 'windows'
        os:
          - 'linux-appimage'
          - 'linux-archlinux'
          - 'linux-deb'
          - 'linux-rpm'
          - 'linux-tgz'
          - 'macos'
          - 'windows'
  release:
    needs: 'build'
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-24.04'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: 'Get artifacts'
        uses: 'actions/download-artifact@v8'
        with:
          merge-multiple: true
          path: './out'
          pattern: 'metadata-editor-*'
      - name: 'Configure Git'
        run: |
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - id: 'description'
        name: 'Prepare release description'
        run: |
          d=$(cat RELEASE.md)
          d=${d//'%'/'%25'}
          d=${d//$'\n'/'%0A'}
          d=${d//$'\r'/'%0D'}
          echo "description=$d" >>"$GITHUB_OUTPUT"
      - name: 'Create release'
        uses: 'svenstaro/upload-release-action@v2'
        with:
          body: '${{ steps.description.outputs.description }}'
          file: './out/*'
          file_glob: true
          release_name: '基板IDチェンジャー v${{ needs.build.outputs.version }}'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          tag: '${{ needs.build.outputs.version }}'
name: 'Build and Release'
on:
  workflow_dispatch:
